spring.application.name=cart
#spring.datasource.url=jdbc:postgresql://localhost:5432/product_ms
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
api.headers.config.baseUrl=https://real-time-amazon-data.p.rapidapi.com/
api.headers.config.key=X-RapidAPI-Key
api.headers.config.value=2b7d719a6emshc865030ef65fe01p1d8b17jsncbf82267fa49



spring.datasource.url=jdbc:h2:mem:class11_ques4
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

